spring:
  # 当不加 dynamic 配置时，仍可以使用以下单一数据源配置，切换方便
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tmsp?characterEncoding=utf8&usSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: njxnet1234
    driverClassName: com.mysql.cj.jdbc.Driver

mybatis-plus:
  # 类型转换，主要是枚举类转换用
  # type-handlers-package: com.njxnet.service.tmsp.config.constant.mybatis
  mapper-locations: classpath:mappers/*xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启sql日志
    # org.apache.ibatis.logging.slf4j.Slf4jImpl 这个日志可以输出到日志文件中